### ISSUE TITLE
Interesting

### ISSUE THREAD

**Issue by ArjixWasTaken** [Jacekun/CloudStream-3XXX#1]
Should I copy the hentai providers from my fork and place them here?
Keeping my fork up to date is tiring.

(And if you want, to also copy the crunchyroll provider as well.)

**Comment by Jacekun** [comment]
You can open an PR and I'll merge it.

Honestly, I don't plan to release any apk with this fork, this is mostly for personal use but you can contribute to it if you want. Hentai providers sounds cool too

**Comment by ArjixWasTaken** [comment]
> Honestly, I don't plan to release any apk with this fork

Want me to add my signature so that the workflow can build?
I believe a fork that is maintained by two people is better than a fork maintained by one person.
Since...as you can see my fork is semi-abandoned.

**Comment by Jacekun** [comment]
Yeah, go for it

**Comment by ArjixWasTaken** [comment]
uhh, do you have a discord? or are you in the discord server for ease of communication?

And uhh, I can't add to the repo secrets as a collaborator, you will either have to add them urself or move this repo to an org and make me an owner as well.

**Comment by Jacekun** [comment]
@ArjixWasTaken  Message we at Jace#7393
