### ISSUE TITLE
[Provider] Some sites

### ISSUE THREAD

**Issue by OshekharO** [Jacekun/CloudStream-3XXX#18]
Here are some sites i managed to find. Feel free to cross off sites that are not feasible to implement.

### Animes:

- [ ] https://anime-world.in
- [ ] https://lmanime.com
- [ ] https://animexin.xyz
- [ ] https://123animes.ru
- [ ] https://animenana.com
- [ ] https://animefox.sbs
- [ ] https://animeonsen.xyz
- [ ] https://11anime.fr
- [ ] https://www2.kickassanime.ro
- [ ] https://kimcartoon.li
- [ ] https://animeflick.net
- [ ] https://www.animeworld.tv

### Movies & Series:

- [ ] https://ecinema.ml
- [ ] https://moviesee.live
- [ ] https://turkish123.com
- [ ] https://www.privatehd.xyz
- [ ] https://shoow.in
- [ ] https://movie.squeezebox.dev
- [ ] https://cmovies.online
- [ ] https://prettyflix.gq
- [ ] http://www.streamlord.com
- [ ] https://theflix.to

**Comment by Jacekun** [comment]
You didn't read the issue checklist, did you?

Anyways, closing since these requests need to be made in the upstream.
