### ISSUE TITLE
[Provider] Add 'OnlineMoviesHindi'

### ISSUE THREAD

**Issue by OshekharO** [Jacekun/CloudStream-3XXX#27]
**Guidelines:**
- [x] It **is not** a duplicate issue.
- [x] It **does not** exist on [Cloudstream 3](https://github.com/LagradOst/CloudStream-3).
- [x] It **is not** requested, nor is a planned feature on [Cloudstream 3](https://github.com/LagradOst/CloudStream-3).
- [x] It **is** Not an adult site.
- [x] It **does not** have reCaptcha, CloudFare protection, or any annoying web protections.

**Info:**
- Name: OnlineMoviesHindi
- Link: https://111.90.159.132/
- Language: Hindi
- Description: huge collection of hindi dubbed and original Movies with download option.

**Comment by Jacekun** [comment]
Movie site requests should be done [on here](https://github.com/LagradOst/CloudStream-3/issues/24).

Will close now.
