### ISSUE TITLE
[Bug] Many Sites show coming soon but it plays in the website

### ISSUE THREAD

**Issue by Adbc3949** [Jacekun/CloudStream-3XXX#39]
**Guidelines:**
- [x] It **is not** a duplicate issue.
- [x] It **does not** exist on [Cloudstream 3](https://github.com/LagradOst/CloudStream-3) Issues tab.
- [x] If provider bug, **it is exclusively** on this Fork.
- [x] If related to a provider, I have checked the site and it works, but not the app.

**Describe the bug** <br>

**To Reproduce** <br>
*(Sample only, change the steps*)

**Expected behavior** <br>

**Screenshots** <br>

**Device (please complete the following information):**
 - Android Version: [e.g. Android 11 API 30]
 - App Version: [e.g. r1026]
 - Provider: [e.g. JAV HD]
 - Link: [Actual link copied to clipboard from the App]

**Additional context** <br>

**Comment by Jacekun** [comment]
1. Messy issue. Follow the template and guidelines.
2.  Read the main page for Info. Most providers haven't got streaming implemented yet. Mostly for searching only.
