### ISSUE TITLE
[Feature] dev/pre-build versions relative to cloudstream-3 base pre-release

### ISSUE THREAD

**Issue by bachig26** [Jacekun/CloudStream-3XXX#58]
### Guidelines

- [X] It **is not** a duplicate issue.
- [X] It **does not** exist on [Cloudstream 3](https://github.com/LagradOst/CloudStream-3) Issues tab.
- [X] It **is not** requested, nor is a planned feature on [Cloudstream 3](https://github.com/LagradOst/CloudStream-3).
- [X] It **is not** a request to add a website. Use [specific template](https://github.com/Jacekun/CloudStream-3XXX/issues/new?labels=provider&template=cs3xxx_provider_request.yml&title=%5BProvider%5D+ChangeThisTitle) for this.

### Type of feature (Primary)

Others

### Request Descrption

This issue is to request for a pre-build version relative to main cloudstream-3 pre-release.

**Comment by Jacekun** [comment]
It'll come in the next few days. Merging from cs3 base is not easy to be automated as merge conflicts are bound to happen. Just wait for it.
