### ISSUE TITLE
Site Addition Request

### ISSUE THREAD

**Issue by imurreflection** [Jacekun/CloudStream-3XXX#59]
Hi, Thanks for this add-on. Is it possible to add

https://yomovies.lol/ 

as we don't have any Indian language provider in either in CS3 or in Beta release and one available is not working anymore and there has been no response.

**Comment by Jacekun** [comment]
No. Request it on the main app. Read the guidelines when submitting issues.

The main reason I don't accept such requests is that I merge with main and as such, it'll eventually be merged into this fork. I don't want to deal with conflicts due to duplicate providers.
