### ISSUE TITLE
Add YouTube

### ISSUE THREAD

**Issue by LincCodes** [Jacekun/CloudStream-3XXX#61]
### Guidelines

- [X] It **is not** a duplicate issue.
- [X] It **does not** exist on [Cloudstream 3](https://github.com/LagradOst/CloudStream-3) Issues tab.
- [X] It **is not** requested, nor is a planned feature on [Cloudstream 3](https://github.com/LagradOst/CloudStream-3).
- [X] It **is not** a request to add a website. Use [specific template](https://github.com/Jacekun/CloudStream-3XXX/issues/new?labels=provider&template=cs3xxx_provider_request.yml&title=%5BProvider%5D+ChangeThisTitle) for this.

### Type of feature (Primary)

Site Extractor

### Request Descrption

Just out of curiosity, is it possible to add YouTube to Cloudstream?

**Comment by Jacekun** [comment]
It *might* be possible, but I **would not** add it as there are better Youtube client than CloudStream.

**Comment by LincCodes** [comment]
The one's I'm familiar with are PureTube, Vidmate and SnapTube but have a terrible connect when the network is 3G.... Any other YouTube client alternatives?
