### ISSUE TITLE
[Feature] apps not working

### ISSUE THREAD

**Issue by raged2214** [Jacekun/CloudStream-3XXX#63]
### Guidelines

- [X] It **is not** a duplicate issue.
- [X] It **does not** exist on [Cloudstream 3](https://github.com/LagradOst/CloudStream-3) Issues tab.
- [X] It **is not** requested, nor is a planned feature on [Cloudstream 3](https://github.com/LagradOst/CloudStream-3).
- [X] It **is not** a request to add a website. Use [specific template](https://github.com/Jacekun/CloudStream-3XXX/issues/new?labels=provider&template=cs3xxx_provider_request.yml&title=%5BProvider%5D+ChangeThisTitle) for this.

### Type of feature (Primary)

Others

### Type of feature (Secondary)

Others

### Request Descrption

the app stop working after playing some movies  i think because cloudstream 3 update. and can you make the jav to work?some are coming soon. nor not play.hehe

### Other info

fix the apps please

**Comment by Jacekun** [comment]
- Try the pre-release if the stable version isn't working
- 'Coming Soon' means the site is WIP and does not have working streams.
- Some providers rely heavily on specific extractor logic. If that logic fails, then no stream will work. Try another site.

**Comment by raged2214** [comment]
can you put this in the same row of home search button? for better use in android tv box?
![received_3296266043954781](https://user-images.githubusercontent.com/109159351/181235333-4436ec93-3539-45fa-ab51-1f4c8c2b3e83.jpeg)
