### ISSUE TITLE
Horizontal banners

### ISSUE THREAD

**Issue by venkat2305** [Jacekun/CloudStream-3XXX#64]
### Guidelines

- [X] It **is not** a duplicate issue.
- [X] It **does not** exist on [Cloudstream 3](https://github.com/LagradOst/CloudStream-3) Issues tab.
- [X] It **is not** requested, nor is a planned feature on [Cloudstream 3](https://github.com/LagradOst/CloudStream-3).
- [X] It **is not** a request to add a website. Use [specific template](https://github.com/Jacekun/CloudStream-3XXX/issues/new?labels=provider&template=cs3xxx_provider_request.yml&title=%5BProvider%5D+ChangeThisTitle) for this.

### Type of feature (Primary)

UI/UX

### Type of feature (Secondary)

UI/UX

### Request Descrption

Can you add horizontal banners when applicable. Right now the posters are cropped. 
1.Please add horizontal banners in home tab, search results 
2.if possible add the horizontal banners in content page(whatever everyone calls it, see the image below for reference).
![IMG_20220727_111804](https://user-images.githubusercontent.com/55329452/181170980-47f14579-b87b-4b81-ae1a-40b7ec575766.jpg)

Thank you for your time

**Comment by raged2214** [comment]
can i give you some love m3u file?working on ph.

**Comment by Jacekun** [comment]
There's already a similar request on the main project.

The short of it is that images are dependent on sites if they provide it. And as not all of them have banners, it will look awful to add.

If in the future the main project adds it, it will eventually be merged into this fork. Please wait til then.

**Comment by Jacekun** [comment]
> can i give you some love m3u file?working on ph.

Please don't hijack the issue and create a separate one. Also, if m3u8 is available on phub, I might look into it. But its low prio since I'm planning on adding a provider first
