### ISSUE TITLE
fix app icon

### ISSUE THREAD

**Issue by bachig26** [Jacekun/CloudStream-3XXX#65]
### Guidelines

- [X] It **is not** a duplicate issue.
- [X] It **does not** exist on [Cloudstream 3](https://github.com/LagradOst/CloudStream-3) Issues tab.
- [X] It **is not** requested, nor is a planned feature on [Cloudstream 3](https://github.com/LagradOst/CloudStream-3).
- [X] It **is not** a request to add a website. Use [specific template](https://github.com/Jacekun/CloudStream-3XXX/issues/new?labels=provider&template=cs3xxx_provider_request.yml&title=%5BProvider%5D+ChangeThisTitle) for this.

### Type of feature (Primary)

UI/UX

### Request Descrption

The app icon reflects the upstream, not the 3XXX.

**Comment by Jacekun** [comment]
If its the pre-release, its intended

**Comment by bachig26** [comment]
> If its the pre-release, its intended

Okay
