### ISSUE TITLE
[Bug] 9anime

### ISSUE THREAD

**Issue by iCeY3** [Jacekun/CloudStream-3XXX#68]
### Guidelines

- [X] It **is not** a duplicate issue.
- [X] It **does not** exist on [Cloudstream 3](https://github.com/LagradOst/CloudStream-3) Issues tab.
- [X] If provider bug, **it is exclusively** on this Fork.
- [X] If related to a provider, I have checked the site and it works, but not the app.

### Description

9anime.id doesnt work
![Screenshot_20220807-023058_CloudStream 3XXX](https://user-images.githubusercontent.com/98146929/183268986-391f6f67-652c-431c-afc9-8b482aace83c.jpg)

### Expected Behaviour

Needs fix

### Steps to reproduce

Main page

### Android version

12

### Cloudstream version

Latest

### Name and Url of provider

9anime.id

**Comment by Jacekun** [comment]
Report it on main repo.
